### ISSUE TITLE
Unable to query booking if itinerary instance is disposed

### ISSUE THREAD

**Issue by jochenvanwylick** [tamasvajk/SkyScanner#11]
In my app - I'm querying flights and passing it down to the view. In case I need to display booking details - however - I don't have the itinerary instance anymore. 

I need this in order to query the booking:

````
Task<BookingResponse> QueryBooking(Itinerary itinerary);
````

However - it's not available anymore and I cannot create it, since the constructor is internal. I propose to add to `IScanner` the following: 

````
Task<BookingResponse> QueryBooking(BookingQuerySettings bookingQuerySettings);
````

Which I have to make public and which I'll give a static method that instantiates it with sessionkey, leg ids and adults/children/infants as params - since those are the required parameters for querying bookings. Is that OK?

**Comment by jochenvanwylick** [comment]
@tamasvajk This also implies I have to roundtrip the SessionId to the client I see.

**Comment by jochenvanwylick** [comment]
@tamasvajk Hey Tamas - so could you implement this in the way you had in mind? I would really appreciate that - because I don't want to use my own 'fork'

**Comment by tamasvajk** [comment]
@jochenvanwylick I couldn't find the time this week to do it, and next week will be busy too. Sorry for the delay, I'll try to do it next week, but can't promise it. :-(
