### ISSUE TITLE
Flights_Correspond_To_Query fails

### ISSUE THREAD

**Issue by tamasvajk** [tamasvajk/SkyScanner#14]
The test fails firstly because of not being able to find any itinerary corresponding to the query.

If the max duration is increased to 30 hours, then it fails when checking the inbound legs. The segment  endings and stops don't match.

**Comment by tamasvajk** [comment]
@jochenvanwylick I didn't have enough time this morning to investigate this issue. The [SkyScanner test harness](http://business.skyscanner.net/portal/en-GB/Documentation/FlightsLivePricingQuickStart) returns properly the result for the same query.

Also, it seemed that the SkyScanner site has two itineraries while we only have one.

**Comment by jochenvanwylick** [comment]
:+1:
