### ISSUE TITLE
Add search overloads that take in CancellationToken

### ISSUE THREAD

**Issue by jochenvanwylick** [tamasvajk/SkyScanner#18]
Once a search is fired off - there is no way to cancel the search process. I would suggest we add an overload to the search methods that takes in a cancellation token - which will stop the polling process in the background.

We're seeing a bunch of users that fire off wrong searches or decide to change their search mid-search. In order to save resources - I would like to be able to cancel the process.

Something along the lines of 

`Task<List<Itinerary>> QueryFlight(FlightQuerySettings flightQuerySettings, CancellationToken token);`

**Comment by tamasvajk** [comment]
Good idea @jochenvanwylick. 

Off:
Sorry I was not too responsive lately on the other open issues. I owe you at least one fix for two weeks now. I'm on my way of implementing these.

**Comment by jochenvanwylick** [comment]
@tamasvajk No worries !
