### ISSUE TITLE
Running the SkyScanner.Console app results in exception in SearchDetailed method

### ISSUE THREAD

**Issue by jochenvanwylick** [tamasvajk/SkyScanner#2]
The line after

    var bookingQueryTasks = itineraries.Select(scanner.QueryBooking);

in `Program.cs` in `SkyScanner.Console` causes a whole series of `HTTP 410` on my machine. The PUT requests seem completely valid - I checked with docs ( http://business.skyscanner.net/portal/en-GB/Documentation/FlightsLivePricingList )

````
PUT http://partners.api.skyscanner.net/apiservices/pricing/v1.0/9d46da7adde7413faee7f2108db4199e_ecilpojl_193122C2B08EEC1444D299431B275CDE/booking HTTP/1.1
Accept: application/json
Content-Type: application/x-www-form-urlencoded
Host: partners.api.skyscanner.net
Content-Length: 144
Expect: 100-continue

OutboundLegId=13554-1508040840-UA-0-11442-1508041135&InboundLegId=11442-1508110905-UA-0-13554-1508112120&apiKey=--removed api key--
````

Response

````
HTTP/1.1 410 Gone
Cache-Control: private
Content-Length: 54
Content-Type: application/json
Date: Tue, 28 Jul 2015 16:22:39 GMT

{"ValidationErrors":[{"Message":"Validation Errors"}]}
````

Also the content I checked against the preceding GET call. I'll see if I can find the problem tomorrow, create fix and send pull req.

**Comment by tamasvajk** [comment]
@jochenvanwylick If you can't find the issue, I'll look into it at some point.
Just a pointer 410 means that the [session is gone](http://business.skyscanner.net/portal/en-GB/Documentation/Faq#qf3). Did you get it immediately after querying the itinerary?

**Comment by jochenvanwylick** [comment]
Yeah, I saw that too in the docs. It happens during execution of the console app. I updated the departure dates since they were somewhere in June, but other than that, I haven't changed anything.

**Comment by tamasvajk** [comment]
@jochenvanwylick I found the issue:
In the [Booking.cs](https://github.com/tamasvajk/SkyScanner/blob/master/src/SkyScanner/Services/Booking.cs) you have to change the URL from http://partners.api.skyscanner.net to http://business.skyscanner.net. The doc says that the first one should be used, but it doesn't work as expected.

I'm not sure if it is temporary or not, I'll try to contact SkyScanner tomorrow.

**Comment by jochenvanwylick** [comment]
OK cool - let me know what you find. Just as extra info - here's fiddler:

![2015-07-29 10_24_14-fiddler web debugger](https://cloud.githubusercontent.com/assets/3002474/8953024/24c2769a-35dc-11e5-8e56-5b8fa899ba4b.png)

**Comment by tamasvajk** [comment]
@jochenvanwylick I found the issue with Fiddler too. If you simply "Reissue and Edit" an entry, and change the Host to business.skyscanner.net, the booking query is accepted, and correctly answered. 

I've contacted SkyScanner with the issue, I hope they'll answer.

**Comment by tamasvajk** [comment]
@jochenvanwylick Hah, I just found that the Flight service was actually querying from business.skyscanner.net. So I changed it to the partners.api..., and it seems to me that it is working correctly. 

(I was most probably lucky before and the two URLs pointed to the same server.)

**Comment by jochenvanwylick** [comment]
@tamasvajk OK - perfect - closing issue. Could you please look at the pull-request I sent? It would be great if you could downgrade the .NET framework version. That saves me updating 60+ projects.
