### ISSUE TITLE
OnInterimResultsRecieved is not called for final poll

### ISSUE THREAD

**Issue by jochenvanwylick** [tamasvajk/SkyScanner#8]
In my current implementation, when searching for a flight, I'm:
- listening to `OnInterimResultsRecieved` events an push new- and updated-flights to the client
- pushing everything *again* to the client - as soon as the search completes

That means I'm sending duplicate data down - which should not be necessary. I'm forced to do this, since `OnInterimResultsRecieved` doesn't fire on the last poll. See implementation:

````
if (response.Succeeded)
{                        
    return response;
}

OnInterimResultsRecieved?.Invoke(this, response);
````

How do you suggest we fix this? Should we add a flag to `InterimChangeSet` to indicate that it's the final changeset - and call `OnInterimResultsRecieved` once more on the finall poll? Or change the returntype of `QueryFlight` to return a `changeset` - so I can choose to only use the additions- and updates? 

@tamasvajk - what do you suggest I do? I can build it and send a PR.

**Comment by tamasvajk** [comment]
I would probably use a flag. That seems the easiest solution, and it doesn't break previous code that is just using the final result.

**Comment by jochenvanwylick** [comment]
@tamasvajk : could you please advice where you want me to put the flag. There's quite a bit of interfaces and generic things and I don't want to mess with your code style.

**Comment by tamasvajk** [comment]
Good question. I would probably change `delegate void InterimResultsRecieved<in T>(object sender, T args)` to `delegate void EventHandler<TEventArgs>(object sender, TEventArgs e)` where TEventArgs would be some class that has the flag, and the `response`.

WDYT?

**Comment by jochenvanwylick** [comment]
@tamasvajk OK - sounds good - I'll work on it
