### ISSUE TITLE
Unable to use different Currency without querying currencies first

### ISSUE THREAD

**Issue by jochenvanwylick** [tamasvajk/SkyScanner#9]
As it is - I cannot query SkyScanner with the EUR currency - without querying all currencies first. In order to query in EUR, I now have to:

````
var currencies = await scanner.QueryCurrency();
var currentCurrency = currencies.FirstOrDefault(currency => currency.Code == "EUR");
....
var settings = new FlightResponseSettings(..., currentCurrency);
var itineraries = await scanner.QueryFlight(settings);
````

If you want to keep the `Currency.Code` modifier internal ( which makes sense ), how about we add:

````
public static Currency FromCode(string code) {
    return new Currency() { Code = code }
}
````

To `Currency.cs`  ? That will save me a bunch of HTTP calls. Or we add it as constructor arguments - whichever you prefer.

**Comment by tamasvajk** [comment]
Sounds good, that's what I did with the locations. https://github.com/tamasvajk/SkyScanner/blob/1fce0248f932d19af94d9215ef8abbc7dac153b7/src/SkyScanner/Data/Location.cs
